apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  template:
    metadata:
      name: postgres-pod
      labels:
        type: postgres-database
    spec:
      containers:
      - name: postgres
        image: postgres
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          value: "test"
        - name: POSTGRES_DB
          value: "school"
  replicas: 1
  selector:
    matchLabels:
      type: postgres-database