spring:
  application:
    name: StudentService
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://${DATABASE_URL}:${DATABASE_PORT}/school"
    username: ${USERNAME}
    password: ${PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL95Diaclect

server:
  port: ${SERVICE_PORT}